apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: staging
data:
  NODE_ENV: "staging"
  PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  NODE_ENV: "production"
  PORT: "8080"

