apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: staging
type: Opaque
stringData:
  APP_SECRET: "change-this-before-real-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: production
type: Opaque
stringData:
  APP_SECRET: "change-this-before-real-production"
