name: Build and Push Docker Image

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout exact commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/niraj-mx07/devops-k8s-cicd-platform:latest
            ghcr.io/niraj-mx07/devops-k8s-cicd-platform:${{ github.event.workflow_run.head_sha }}